import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Table, Td, Th } from "@/components/ui/table";
import { formatCurrency, formatDate } from "@/lib/utils";
export default async function MembersPage({ searchParams }: { searchParams: { q?: string; status?: string } }) {
  const q = searchParams.q;
  const members = await prisma.memberProfile.findMany({ where: { AND: [q ? { OR: [{ firstName: { contains: q, mode: "insensitive" } }, { lastName: { contains: q, mode: "insensitive" } }, { mobile: { contains: q } }, { memberCode: { contains: q } }] } : {}, searchParams.status ? { status: searchParams.status as any } : {}] }, include: { memberships: { where: { status: "ACTIVE" }, include: { plan: true }, take: 1 } }, orderBy: { createdAt: "desc" } });
  return <div className="space-y-6"><div className="flex items-center justify-between"><h1 className="text-3xl font-black">لیست اعضا</h1><Link href="/admin/members/new" className="rounded-xl bg-mint px-4 py-2 font-bold">عضو جدید</Link></div><Card><form className="grid gap-3 md:grid-cols-5"><input name="q" placeholder="جستجو نام، موبایل، کد" className="rounded-xl border p-2 md:col-span-2" defaultValue={q}/><select name="status" className="rounded-xl border p-2"><option value="">همه وضعیت‌ها</option><option value="ACTIVE">فعال</option><option value="INACTIVE">غیرفعال</option><option value="BLOCKED">مسدود</option><option value="EXPIRED">منقضی</option></select><select className="rounded-xl border p-2"><option>همه رشته‌ها</option></select><button className="rounded-xl bg-charcoal px-4 py-2 text-white">فیلتر</button></form></Card><Table><thead><tr><Th>کد</Th><Th>نام</Th><Th>موبایل</Th><Th>وضعیت</Th><Th>پلن فعال</Th><Th>جلسات باقی‌مانده</Th><Th>تراز</Th><Th>امتیاز</Th><Th>آخرین تردد</Th><Th>عملیات</Th></tr></thead><tbody>{members.map(m => <tr key={m.id}><Td>{m.memberCode}</Td><Td>{m.firstName} {m.lastName}</Td><Td>{m.mobile}</Td><Td><Badge tone={m.status === "ACTIVE" ? "success" : "warning"}>{m.status}</Badge></Td><Td>{m.memberships[0]?.plan.title ?? "—"}</Td><Td>{m.memberships[0]?.remainingSessions ?? 0}</Td><Td>{formatCurrency(m.balance)}</Td><Td>{m.loyaltyPoints}</Td><Td>{formatDate(m.lastAttendanceAt)}</Td><Td><Link className="text-mint font-bold" href={`/admin/members/${m.id}`}>مشاهده</Link></Td></tr>)}</tbody></Table></div>;
}
