import Link from "next/link";
import { Card, CardTitle } from "@/components/ui/card";
import { Table, Td, Th } from "@/components/ui/table";
import { AttendanceChart, PieStat, RevenueChart } from "@/components/admin/charts";
import { prisma } from "@/lib/prisma";
import { formatCurrency, formatDate } from "@/lib/utils";

export default async function AdminDashboard() {
  const [members, payments, leads, attendances, classes, activeMembers, inactiveMembers, products] = await Promise.all([
    prisma.memberProfile.findMany({ take: 5, orderBy: { createdAt: "desc" }, include: { memberships: { include: { plan: true }, orderBy: { createdAt: "desc" }, take: 1 } } }),
    prisma.payment.findMany({ take: 5, orderBy: { createdAt: "desc" }, include: { member: true } }),
    prisma.lead.findMany({ take: 5, orderBy: { createdAt: "desc" } }),
    prisma.attendance.count({ where: { checkInAt: { gte: new Date(new Date().setHours(0,0,0,0)) } } }),
    prisma.classSchedule.count(), prisma.memberProfile.count({ where: { status: "ACTIVE" } }), prisma.memberProfile.count({ where: { status: { not: "ACTIVE" } } }), prisma.productSale.aggregate({ _sum: { totalAmount: true } })
  ]);
  const todaySales = payments.reduce((s, p) => s + Number(p.amount), 0);
  const cards = [["فروش امروز", formatCurrency(todaySales)], ["جمع صندوق امروز", formatCurrency(todaySales)], ["ثبت‌نام‌های جدید", members.length], ["تمدیدهای نزدیک", "۸"], ["اعضای بدهکار", await prisma.memberProfile.count({ where: { balance: { gt: 0 } } })], ["اعضای فعال", activeMembers], ["اعضای غیرفعال", inactiveMembers], ["تردد امروز", attendances], ["کلاس‌های امروز", classes], ["ظرفیت کلاس‌ها", "۷۴٪"], ["درآمد مربیان", formatCurrency(24000000)], ["فروش محصولات", formatCurrency(products._sum.totalAmount ?? 0)], ["لیدهای جدید سایت", leads.length], ["ثبت‌نام‌های رو به اتمام", await prisma.membership.count({ where: { status: "ACTIVE", endDate: { lte: new Date(Date.now()+7*86400000) } } })]];
  return <div className="space-y-6"><div className="flex items-center justify-between"><h1 className="text-3xl font-black">داشبورد مدیریت</h1><Link className="rounded-xl bg-mint px-4 py-2 font-bold" href="/admin/members/new">عضو جدید</Link></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value]) => <Card key={label as string}><p className="text-sm text-gray-500">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></Card>)}</div><div className="grid gap-4 xl:grid-cols-2"><Card><CardTitle>درآمد ماهانه</CardTitle><RevenueChart data={["فروردین","اردیبهشت","خرداد","تیر","مرداد","شهریور"].map((name,i)=>({name,value:(i+2)*9000000}))}/></Card><Card><CardTitle>روند تردد</CardTitle><AttendanceChart data={["ش","ی","د","س","چ","پ"].map((name,i)=>({name,value:12+i*3}))}/></Card><Card><CardTitle>ثبت‌نام بر اساس رشته</CardTitle><PieStat data={[{name:"پیلاتس",value:32},{name:"یوگا",value:21},{name:"فانکشنال",value:18},{name:"TRX",value:12}]}/></Card><Card><CardTitle>توزیع امتیاز وفاداری</CardTitle><PieStat data={[{name:"Bronze",value:14},{name:"Silver",value:6},{name:"Gold",value:4},{name:"VIP",value:1}]}/></Card></div><div className="grid gap-4 xl:grid-cols-2"><Card><CardTitle className="mb-4">آخرین اعضا</CardTitle><Table><thead><tr><Th>کد</Th><Th>نام</Th><Th>پلن</Th><Th>تاریخ</Th></tr></thead><tbody>{members.map(m=><tr key={m.id}><Td>{m.memberCode}</Td><Td>{m.firstName} {m.lastName}</Td><Td>{m.memberships[0]?.plan.title ?? "—"}</Td><Td>{formatDate(m.createdAt)}</Td></tr>)}</tbody></Table></Card><Card><CardTitle className="mb-4">آخرین پرداخت‌ها</CardTitle><Table><thead><tr><Th>عضو</Th><Th>مبلغ</Th><Th>وضعیت</Th><Th>تاریخ</Th></tr></thead><tbody>{payments.map(p=><tr key={p.id}><Td>{p.member.firstName} {p.member.lastName}</Td><Td>{formatCurrency(p.amount)}</Td><Td>{p.status}</Td><Td>{formatDate(p.createdAt)}</Td></tr>)}</tbody></Table></Card><Card><CardTitle className="mb-4">عضویت‌های رو به اتمام</CardTitle><Table><thead><tr><Th>عضو</Th><Th>پایان</Th><Th>جلسات</Th></tr></thead><tbody>{members.map(m=><tr key={m.id}><Td>{m.firstName} {m.lastName}</Td><Td>{formatDate(m.memberships[0]?.endDate)}</Td><Td>{m.memberships[0]?.remainingSessions ?? 0}</Td></tr>)}</tbody></Table></Card><Card><CardTitle className="mb-4">لیدهای جدید سایت</CardTitle><Table><thead><tr><Th>نام</Th><Th>موبایل</Th><Th>منبع</Th></tr></thead><tbody>{leads.map(l=><tr key={l.id}><Td>{l.fullName}</Td><Td>{l.mobile}</Td><Td>{l.source}</Td></tr>)}</tbody></Table></Card></div></div>;
}
